stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python manage.py test

#staging:
#  stage: deploy
#  script:
#    -
#  only:
#    -
#
#production:
#  stage: deploy
#  script:
#    -
#  only:
#    -